Repository ha3158987/sidedish, pull requests merged in 2021-04, with the labels that each got.

#2 [#1] 개발 환경 구축 완료
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/App.css
  src/App.js
  src/index.css
  src/index.js
Labels: setting

#4 [#3] Header 구현 완료
  src/App.css
  src/App.js
  src/component/Header.jsx
  src/index.css
  src/style.js
Labels: feature, setting, style

#6 [#5] feat: :sparkles: BestTab UI 구현
  src/App.js
  src/component/Header.jsx
  src/component/bestTab/BestItem.jsx
  src/component/bestTab/BestItems.jsx
  src/component/bestTab/BestTab.jsx
  src/component/bestTab/BestTabContainer.jsx
  src/component/bestTab/BestTabNavigator.jsx
  src/component/util/ItemCard.jsx
  src/component/util/Label.jsx
  src/const.js
  src/index.css
Labels: feature, setting, style

#11 [#10] feat: :sparkles: Header Dropdown 구현
  src/App.js
  src/component/Header.jsx
  src/component/header/Header.jsx
  src/component/header/HeaderLeft.jsx
  src/component/header/HeaderRight.jsx
  src/component/header/Navigations.jsx
Labels: feature, style

#14 API 데이터 fetch 요청 + 베스트 반찬 tab 랜덤 출력
  src/api.js
  src/component/bestTab/BestItems.jsx
  src/component/bestTab/BestTab.jsx
  src/component/bestTab/BestTabContainer.jsx
  src/component/bestTab/BestTabNavigator.jsx
  src/component/util/ItemCard.jsx
  src/component/util/Label.jsx
Labels: feature, style

#18 [#15] feat: :sparkles: 상세 modal 페이지 UI 구현
  src/App.js
  src/component/popUp/PopUpContainer.jsx
  src/component/popUp/PopUpImages.jsx
  src/component/popUp/PopUpInformations.jsx
  src/component/slideContainer/SlideContainer.jsx
Labels: feature, style

#20 Team19/16
  src/App.js
  src/component/bestTab/BestItems.jsx
  src/component/bestTab/BestTab.jsx
  src/component/bestTab/BestTabContainer.jsx
  src/component/popUp/PopUpContainer.jsx
  src/component/popUp/PopUpImages.jsx
  src/component/popUp/PopUpInformations.jsx
  src/component/popUp/PopUpItemCountContainer.jsx
  src/component/slideContainer/SlideContainer.jsx
  src/component/slideContainer/SlideItems.jsx
  src/component/util/ItemCard.jsx
Labels: feature, style

#22 [#19] refactor: :hammer: 리팩토링
  src/App.js
  src/common/api.js
  src/common/const.js
  src/common/style.js
  src/component/Context.jsx
  src/component/bestTab/BestItems.jsx
  src/component/main/Main.jsx
  src/component/main/ShowMoreBtn.jsx
  src/component/main/bestTab/BestItems.jsx
  src/component/main/bestTab/BestTab.jsx
  src/component/main/bestTab/BestTabContainer.jsx
  src/component/main/bestTab/BestTabNavigator.jsx
  src/component/main/popUp/PopUpContainer.jsx
  src/component/main/popUp/PopUpImages.jsx
  src/component/main/popUp/PopUpInformations.jsx
  src/component/main/popUp/PopUpItemCountContainer.jsx
  src/component/main/popUp/PopUpItemOrderResult.jsx
  src/component/main/slideContainer/SlideContainer.jsx
  src/component/main/slideContainer/SlideItems.jsx
  src/component/main/slideContainer/SliderArrowBtn.jsx
  src/component/popUp/PopUpContainer.jsx
  src/component/popUp/PopUpImages.jsx
  src/component/popUp/PopUpInformations.jsx
  src/component/popUp/PopUpItemCountContainer.jsx
  src/component/util/ItemCard.jsx
  src/const.js
Labels: refactor, style

#24 Refactoring: 코드 리뷰 코멘트 반영 및 개선
  src/App.js
  src/common/api.js
  src/component/main/bestTab/BestItems.jsx
  src/component/main/bestTab/BestTab.jsx
  src/component/main/bestTab/BestTabContainer.jsx
  src/component/main/bestTab/BestTabNavigator.jsx
  src/component/main/popUp/PopUpContainer.jsx
  src/component/util/dj-slider/DJSlider.jsx
  src/component/util/dj-slider/Slide.jsx
  src/component/util/dj-slider/SlideArrows.jsx
  src/component/util/dj-slider/SlideDot.jsx
  src/component/util/dj-slider/SlideDots.jsx
  src/component/util/dj-slider/SlideList.jsx
Labels: refactor

#26 슬라이드 API 데이터 동기화 + 모든 카테고리 보기 기능 구현
  src/App.js
  src/common/util.js
  src/component/Context.jsx
  src/component/main/Main.jsx
  src/component/main/ShowMoreBtn.jsx
  src/component/main/bestTab/BestItems.jsx
  src/component/main/popUp/PopUpContainer.jsx
  src/component/main/popUp/PopUpImages.jsx
  src/component/main/popUp/PopUpInformations.jsx
  src/component/main/popUp/PopUpItemCountContainer.jsx
  src/component/main/popUp/PopUpItemOrderResult.jsx
  src/component/main/popUp/PopUpItemsSlide.jsx
  src/component/main/slideContainer/SlideItems.jsx
  src/component/main/slideContainer/SliderArrowBtn.jsx
  src/component/util/ItemCard.jsx
  src/component/util/Label.jsx
  src/component/util/dj-slider/DJSlider.jsx
  src/component/util/dj-slider/DicoJsonCarousel.jsx
  src/component/util/dj-slider/Slide.jsx
  src/component/util/dj-slider/SlideArrows.jsx
  src/component/util/dj-slider/SlideDot.jsx
  src/component/util/dj-slider/SlideDots.jsx
  src/component/util/dj-slider/SlideList.jsx
Labels: feature, refactor

#28 BestTab Skeleton UI 만들기
  src/component/main/Main.jsx
  src/component/main/bestTab/BestTab.jsx
  src/component/main/bestTab/BestTabNavigator.jsx
  src/component/main/bestTab/SkeletonTab.jsx
  src/component/util/dj-slider/DicoJsonCarousel.jsx
Labels: feature, style

#30 PopUp Skeleton UI 만들기
  src/component/Context.jsx
  src/component/main/bestTab/BestTab.jsx
  src/component/main/popUp/PopUpContainer.jsx
  src/component/main/popUp/PopUpInformations.jsx
  src/component/main/popUp/PopUpItemsSlide.jsx
  src/component/main/popUp/SkeletonPopUpContainerBody.jsx
Labels: feature
